---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/sandhbolt/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp work.html $DEPLOYPATH
    - /bin/cp services.html $DEPLOYPATH
    - /bin/cp sandhbolt.pdf $DEPLOYPATH
    - /bin/cp gallery.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R photoSwipe $DEPLOYPATH
